CURRENT_SETTINGS_VERSION = 1

VOICE_INTERVAL_MIN = 1
VOICE_INTERVAL_MAX = 120

BEEP_INTERVAL_MIN = 1
BEEP_INTERVAL_MAX = 30

BEEP_PERIOD_IN_FINAL_MIN = 1
BEEP_PERIOD_IN_FINAL_MAX = 20

CYCLE_INTERVAL_ELEMENT_MAX = 59
